### ISSUE TITLE
Project work distribution updated. Have a look at the README

### ISSUE THREAD

**Issue by rifazn** [rifazn/patternlab#2]
@i-jim666 @MFarzad @hossainishtiak We will be tracking our project progress using GitHub issues such as this one. Our first task has been added to the readme, lets try and finish it by tomorrow's class.

**Comment by hossainishtiak** [comment]
oka

**Comment by rifazn** [comment]
I've updated the README.md to reflect what needs to be done in these few days.

1. Would be to make word2idx and idx2word dictionaries from the corpus. For example, for a sentence like "He is a king", "Ces't la vie", we would get a idx2word word2idx like:

```word2idx:
    0: 'He',
    1: 'is',
    2: 'a',
    3: 'king',
    4: "C'est",
    5: 'la',
    6: 'vie'
```
2. Find the right probabilities P(context|center) for all context and center (Although this is almost implemented, I'm taking this one).

**Comment by rifazn** [comment]
Closing the issue as the coursework is completed. The project itself might still see some improvements, might not.
